### ISSUE TITLE
Minishift in part 08 doesn't appear inp revious parts

### ISSUE THREAD

**Issue by NadavAtGitHub** [MLaaS-idfCts/mlaas-trainning-for-rookies#24]
In the exercise the following appears 
"(of course that your full app must be deployed on yor Minishift)."
The openshift section doesn't  require you to create a minishift cluster.

**Comment by itaihay** [comment]
@MLaaS-idfCts/mlaas Which one of you guys was in charge of going though the OC part?
I'm pretty sure it's @RazHoshia
